### ISSUE TITLE
pangolin_lineage_report.txt doesn't parse correctly 

### ISSUE THREAD

**Issue by bl24** [swiftbiosciences/sarscov2analysis_docker#1]
Hello, 

I've noticed that the columns in the pangolin report file do not parse correctly if your cohort of samples contain individuals who fail the QC. I've attached an example of this occurring. 

[pangolin_lineage_report.txt](https://github.com/swiftbiosciences/sarscov2analysis_docker/files/6307390/pangolin_lineage_report.txt)

I have a cohort of 13 samples, with 2 failed samples. I've tried opening this in both Excel and using vi in my terminal window and in both methods, every column to the right of the first column sorts in such a way that there's no gaps where there's a failed sample, which leads to a confusing to interpret document.

**Comment by sand60** [comment]
@bl24 the issue has been fixed. Thanks!
